.TH GP 1 "10 December 1992"
.SH NAME
gp \- PARI calculator
.SH SYNOPSIS
.B gp
[
.B -s
.I stacksize
]
[
.B -p
.I primelimit
]
[
.B -b
.I buffersize
]
.SH DESCRIPTION
Invokes the PARI-GP calculator. It is an advanced programmable calculator.
It computes symbolically as long as possible, numerically where needed.
Its data types are
.TP
numbers
integers, real numbers, exact rational numbers, algebraic numbers,
.IR p "-adic numbers,"
complex numbers,
.TP
modular integers
integers modulo
.IR n .
.TP
polynomials
and rational functions,
.TP
power series
.TP
matrices
and vectors,
.PP
and recursive combinations of these.
.SH USE
.TP
.B ?
to get on-line help.
.TP
.B \\\\q
or
.B EOF
(Ctrl-D)
to quit
.BR gp .
.TP
arrow keys
for editing and viewing the input history.
.SH FILES
.TP
.I gp
main executable
.TP
.I *.gp
gp programs
.SH SEE ALSO
.IR gap (1),
.IR maple (1).
.SH BUGS
.PP
3+O(1)
.SH AUTHORS
C. Batut, D. Bernardi, H. Cohen, M. Olivier.
